version: '3.8'

services:
  postgres:
    container_name: stock-wizard-postgres
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
    - "POSTGRES_USER=stock-wizard"
    - "POSTGRES_PASSWORD=stock-wizard"
    - "POSTGRES_DB=stock-wizard"
    - "PGDATA=/data/postgres"
    volumes:
      - ./data/pg:/data/postgres
  
  app:
    container_name: nestjs-app
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "3333:3333"
    # volumes:
    #   - .:/usr/app
    depends_on:
      - postgres
    links:
      - postgres
  
volumes:
  postgres:
    
